spring:
  application:
    name: x
  datasource:
    url: jdbc:mariadb://localhost:3306/xapp?characterEncoding=utf-8
    username: xapp
    password: xapp
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql